# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('floorConfiguration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.FloorConfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='HouseConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HousePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('floorPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.FloorPlan')),
                ('houseConfiguration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.HouseConfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RoomConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionChoice', models.ManyToManyField(to='houses.Option')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('roomConfiguration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.RoomConfiguration')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='optionTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.OptionType'),
        ),
        migrations.AddField(
            model_name='houseconfiguration',
            name='optionChoice',
            field=models.ManyToManyField(to='houses.Option'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='roomPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.RoomPlan'),
        ),
        migrations.AddField(
            model_name='floorconfiguration',
            name='optionChoice',
            field=models.ManyToManyField(to='houses.Option'),
        ),
    ]
