# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optiontype',
            old_name='draft',
            new_name='cabinets',
        ),
    ]
