# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20180108_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optiontype',
            old_name='cabinets',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='floorConfiguration',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='roomPlan',
        ),
        migrations.RemoveField(
            model_name='houseplan',
            name='floorPlan',
        ),
        migrations.RemoveField(
            model_name='houseplan',
            name='houseConfiguration',
        ),
        migrations.RemoveField(
            model_name='roomplan',
            name='roomConfiguration',
        ),
        migrations.AddField(
            model_name='floorconfiguration',
            name='description',
            field=models.CharField(default='000', max_length=1000),
        ),
        migrations.AddField(
            model_name='floorconfiguration',
            name='floorPlan',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='houses.FloorPlan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floorconfiguration',
            name='houseConfiguration',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='houses.HouseConfiguration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floorconfiguration',
            name='name',
            field=models.CharField(default='000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floorplan',
            name='housePlan',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='houses.HousePlan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floorplan',
            name='name',
            field=models.CharField(default='000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floorplan',
            name='optionChoice',
            field=models.ManyToManyField(to='houses.OptionType'),
        ),
        migrations.AddField(
            model_name='houseconfiguration',
            name='description',
            field=models.CharField(default='000', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houseconfiguration',
            name='housePlan',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='houses.HousePlan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houseconfiguration',
            name='name',
            field=models.CharField(default='000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houseplan',
            name='name',
            field=models.CharField(default='000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houseplan',
            name='optionChoice',
            field=models.ManyToManyField(to='houses.OptionType'),
        ),
        migrations.AddField(
            model_name='option',
            name='description',
            field=models.CharField(default='000', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='name',
            field=models.CharField(default='000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optiontype',
            name='name',
            field=models.CharField(default='000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomconfiguration',
            name='description',
            field=models.CharField(default='000', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomconfiguration',
            name='floorConfiguration',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='houses.FloorConfiguration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomconfiguration',
            name='name',
            field=models.CharField(default='000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomconfiguration',
            name='roomPlan',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='houses.RoomPlan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomplan',
            name='floorPlan',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='houses.FloorPlan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomplan',
            name='name',
            field=models.CharField(default='000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomplan',
            name='optionChoice',
            field=models.ManyToManyField(to='houses.OptionType'),
        ),
    ]
