# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20180115_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='optionChoice',
            field=models.ManyToManyField(to='houses.Option'),
        ),
        migrations.AlterField(
            model_name='houseplan',
            name='optionChoice',
            field=models.ManyToManyField(to='houses.Option'),
        ),
        migrations.AlterField(
            model_name='roomplan',
            name='optionChoice',
            field=models.ManyToManyField(to='houses.Option'),
        ),
    ]
