# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20180115_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='optionTypeID',
            new_name='optionType',
        ),
        migrations.RenameField(
            model_name='roomconfiguration',
            old_name='optionChoice',
            new_name='optionChoices',
        ),
        migrations.RemoveField(
            model_name='floorconfiguration',
            name='optionChoice',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='optionChoice',
        ),
        migrations.RemoveField(
            model_name='houseconfiguration',
            name='optionChoice',
        ),
        migrations.RemoveField(
            model_name='houseplan',
            name='optionChoice',
        ),
        migrations.RemoveField(
            model_name='roomplan',
            name='optionChoice',
        ),
        migrations.AddField(
            model_name='roomplan',
            name='optionTypes',
            field=models.ManyToManyField(to='houses.OptionType'),
        ),
    ]
