# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_auto_20180307_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='imageName',
            field=models.CharField(default='nnn', max_length=100),
            preserve_default=False,
        ),
    ]
