# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_houseconfiguration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='deafultRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.RoomPlan'),
        ),
        migrations.AddField(
            model_name='houseplan',
            name='deafultFloor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.FloorPlan'),
        ),
        migrations.AddField(
            model_name='optiontype',
            name='deafultOption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.Option'),
        ),
        migrations.AlterField(
            model_name='roomplan',
            name='optionTypes',
            field=models.ManyToManyField(null=True, to='houses.OptionType'),
        ),
    ]
