# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_auto_20180317_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='imageName',
            field=models.CharField(default='simpleFloorPlan', max_length=100),
            preserve_default=False,
        ),
    ]
