# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_floorplan_imagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomplan',
            name='heightPosition',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomplan',
            name='leftPosition',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomplan',
            name='topPosition',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomplan',
            name='widthPosition',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
