# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_auto_20180318_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomplan',
            name='topPosition',
            field=models.IntegerField(),
        ),
    ]
