# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_auto_20180318_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomplan',
            name='heightPosition',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomplan',
            name='leftPosition',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomplan',
            name='widthPosition',
            field=models.IntegerField(),
        ),
    ]
