# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_auto_20180318_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
