# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_option_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseplan',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
