# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0016_auto_20180321_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorplan',
            old_name='deafultRoom',
            new_name='defaultRoom',
        ),
        migrations.RenameField(
            model_name='houseplan',
            old_name='deafultFloor',
            new_name='defaultFloor',
        ),
        migrations.RenameField(
            model_name='optiontype',
            old_name='deafultOption',
            new_name='defaultOption',
        ),
        migrations.AlterField(
            model_name='roomconfiguration',
            name='optionChoices',
            field=models.ManyToManyField(null=True, to='houses.Option'),
        ),
    ]
